### ISSUE TITLE
Not an issue but a questions

### ISSUE THREAD

**Issue by bobybob69** [ottopaulsen/MMM-WeConnect#7]
Hey mate 
How are you ? 
Thanks for your module! As I don't have electric car but petrol car, I'm trying to enable this module to work on my MM. 
If it works, would you help me to upgrade your module from battery to both petrol / battery ? 
Perhaps we can add the lock / unlock states for doors, the range for the petrol car, open / close window , etc. Same as their is on the app ? 
What do you think ? 
thanks for your time and support :)

**Comment by ottopaulsen** [comment]
Hi

Sorry, I do not have time to expand this module now, but feel free to submit pull requests if you do changes yourself.

Regards,
Otto
